import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Body from './body'
import Header from './components/Header/Header'
import Sidebar from './components/Sidebar/Sidebar'
// import Profile from './components/Profile'
import { useRouter } from 'next/router'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className={styles.main}>
              <Header/>
              <Sidebar/>
              <Body />
        </main>


      <footer className={styles.footer}>
        {/*  */}
      </footer>
    </div>
  )
}
